
#数据源配置
spring:
  application:
    name: spider8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver            # mysql驱动包
    url: jdbc:mysql://localhost:3306/spider?characterEncoding=utf-8                 # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

#客户端注册进eureka服务列表内
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,http://localhost:7003/eureka
  instance:
    instance-id: spider_provider
    prefer-ip-address: true     #访问路径可以显示IP地址
info:
  app.name: msc-project
  company.name: www.henu.com
  build.artifactId: spider_provider
  build.version: 1.0-SNAPSHOT



  #redis配置,向代码中注入RedisTemplate对象，代替之前所用的Jedis
  redis:
    host: 127.0.0.1    #Redis服务器地址
    port: 6379         #Redis服务器连接端口
    database: 0        #Redis数据库索引（默认为0）
    timeout: 5000      #连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 50  #连接池最大连接数（使用负值表示没有限制）
        max-wait: 3000  #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 20    #连接池中的最大空闲连接
        min-idle: 2     #连接池中的最小空闲连接

#mybatis配置
mybatis:
  config-location: classpath:mybatisConfig.xml        # mybatis配置文件所在路径
  type-aliases-package: com.henu.spider.dao.entity           # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mapper/**/*.xml                         # mapper映射文件

#elasticSearch配置
elasticSearch:
  hostlist: 127.0.0.1:9200
  client:
    connectNum: 10
    connectPerRoute: 50
server:
  port: 8001

