server:
  port: 9001
  context-path: /

feign:
  hystrix:
    enabled: true
#客户端注册进eureka服务列表内
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,http://localhost:7003/eureka
  instance:
    instance-id: msc_feign_consumer_news_9001
    prefer-ip-address: true     #访问路径可以显示IP地址
info:
  app.name: msc-project
  company.name: www.henu.com
  build.artifactId: msc_feign_consumer_news_9001
  build.version: 1.0-SNAPSHOT
#
spring:
  application:
    name: SPIDER9001
